//@version=6
strategy("Strat 19: Keltner Mean Reversion", overlay=true, initial_capital=100000, default_qty_type=strategy.percent_of_equity, default_qty_value=10)
length = 20
mult = 1.5
basis = ta.ema(close, length)
range_1 = ta.atr(10)
upper = basis + range_1 * mult
lower = basis - range_1 * mult
atr = ta.atr(14)

long_cond = low < lower and close > lower
if (long_cond)
    strategy.entry("Long", strategy.long)
    strategy.exit("Exit Long", "Long", stop=low - atr, limit=basis)
